
          
          
          
CREATE         FUNCTION UDF_DATA_RECORD_UPDATE_API(@INSERT_DATE varchar(20))                                      
    RETURNS  @RECORD_VALIDATION_API TABLE (            
                                     
 TABLE_NAME  Varchar(255) ,            
 RECORD_COUNT  BIGINT,            
 INSERT_DATE dATE                                     
 )                                      
 as                                      
                                      
 BEGIN                                       
                                       
  --Declare @INSERT_DATE varchar(20);            
  --set @INSERT_DATE='2023-09-19'            
   -----3B  RAW Tables             
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)            
select 'GST_3B_TMP', count(1) , @INSERT_DATE from [TEST_MPCTD].[dbo].[GST_3B_TMP] where CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE   ;  --1584            
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)            
select 'GSTR_3B_INTER_SUP_PAYMENT_TMP', count(1) , @INSERT_DATE from [TEST_MPCTD]..GSTR_3B_INTER_SUP_PAYMENT_TMP where  CONVERT(DATE, INSERT_DATE,103)=   @INSERT_DATE;  ---125            
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)            
select 'GSTR_3B_INWARD_SUP_TMP',count(1) , @INSERT_DATE from [TEST_MPCTD]..GSTR_3B_INWARD_SUP_TMP  where  CONVERT(DATE, INSERT_DATE,103)=   @INSERT_DATE;             
 INSERT INTO @RECORD_VALIDATION_API  (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)  ---522            
select 'GSTR_3B_ITC_ELIGIBLE_PAYMENT_TMP',count(1) , @INSERT_DATE  from [TEST_MPCTD]..GSTR_3B_ITC_ELIGIBLE_PAYMENT_TMP   where CONVERT(DATE, INSERT_DATE,103)=   @INSERT_DATE;             
 INSERT INTO @RECORD_VALIDATION_API  (TABLE_NAME , RECORD_COUNT ,INSERT_DATE) ---6318            
select 'GSTR_3B_TAXPAYMENT_PD_CASH_TMP',count(1) , @INSERT_DATE  from [TEST_MPCTD]..GSTR_3B_TAXPAYMENT_PD_CASH_TMP  where CONVERT(DATE, INSERT_DATE,103)=   @INSERT_DATE ;             
 INSERT INTO @RECORD_VALIDATION_API  (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)  --840            
select 'GSTR_3B_TAXPAYMENT_PD_ITC_TMP',count(1) , @INSERT_DATE  from [TEST_MPCTD]..GSTR_3B_TAXPAYMENT_PD_ITC_TMP    where CONVERT(DATE, INSERT_DATE,103)=   @INSERT_DATE ;            
 INSERT INTO @RECORD_VALIDATION_API  (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)  --495            
select 'GSTR_3B_TAXPAYMENT_TXPY_TMP',count(1) , @INSERT_DATE from [TEST_MPCTD]..GSTR_3B_TAXPAYMENT_TXPY_TMP   where  CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE ;    ---2192            
            
 --------------GSTR-1 RAW TABLES             
            
  INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)            
 select 'TBL_R1_TXP_AT_INVOICE_AT' , count(1) ,@INSERT_DATE from [TEST_MPCTD]..[TBL_R1_TXP_AT_INVOICE]     WHERE [DTYPE] ='AT' and CONVERT(DATE, INSERT_DATE,103)=   @INSERT_DATE ;             
  INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)  ---5            
 select 'TBL_R1_TXP_AT_INVOICE_TXPD', count(1) , @INSERT_DATE from [TEST_MPCTD]..[TBL_R1_TXP_AT_INVOICE]     WHERE [DTYPE] ='TXPD' and CONVERT(DATE, INSERT_DATE,103)=   @INSERT_DATE ;             
  INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE) ---1              
 select 'TBL_R1_INVOICE_B2B' ,count(1) , @INSERT_DATE from [TEST_MPCTD]..[TBL_R1_INVOICE]     WHERE [DTYPE] ='B2B' and CONVERT(DATE, INSERT_DATE,103)=   @INSERT_DATE ;                
  INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)---101421             
 select 'TBL_R1_INVOICE_B2CL', count(1) , @INSERT_DATE from [TEST_MPCTD]..[TBL_R1_INVOICE]     WHERE [DTYPE] ='B2CL' and CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE  ;              
  INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE) --13            
 select 'TBL_R1_INVOICE_B2CS',  count(1) , @INSERT_DATE from [TEST_MPCTD]..[TBL_R1_INVOICE]     WHERE [DTYPE] ='B2CS' and CONVERT(DATE, INSERT_DATE,103) = @INSERT_DATE  ;              
  INSERT INTO @RECORD_VALIDATION_API  (TABLE_NAME , RECORD_COUNT ,INSERT_DATE) --2361             
 select 'TBL_R1_INVOICE_CDNR' , count(1) , @INSERT_DATE from [TEST_MPCTD]..[TBL_R1_INVOICE]     WHERE [DTYPE] ='CDNR' and CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE  ;              
  INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)  --2814            
 select 'TBL_R1_GST' ,count(1) , @INSERT_DATE from [TEST_MPCTD]..[TBL_R1_GST]   where  CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE  ;         --4965            
            
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)            
 select 'TBL_R1_HSN_DETAILS' ,count(1) , @INSERT_DATE from [TEST_MPCTD]..[TBL_R1_HSN_DETAILS]   where  CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE  ;     ---11905             
            
        
---------------------------GSTR-4 RAW TABLES          
          
          
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)          
SELECT 'RETURN_GSTR_4_TAX_PAID_API' , COUNT(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[Return_GSTR_4_Tax_Paid_TEMP] where  CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE  ;          
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)          
select 'RETURN_GSTR_4_TAX_PAYABLE_API' , count(1) , @INSERT_DATE   FROM [TEST_MPCTD].[dbo].[Return_GSTR_4_Tax_Payable_TEMP]  where  CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE  ;          
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)          
select 'RETURN_GSTR_4_OUTWARD_SUPPLY_API' , count(1) , @INSERT_DATE  FROM [TEST_MPCTD].[dbo].[Return_GSTR_4_TMP] where  CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE  ;          
     
     
    
    
-------------------------GSTIN-7 RAW TABLES  ------        
    
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)       
SELECT 'GSTR_7_TDS_TMP' ,count(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[GSTR_7_TDS_TMP]   where  CONVERT(DATE, INSERT_DATE,103)= @INSERT_DATE    
    
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)       
SELECT 'GSTR_7_TAX_PAID_TMP' ,count(1) , @INSERT_DATE  FROM [TEST_MPCTD].[dbo].[GSTR_7_TAX_PAID_TMP]     where  CONVERT(DATE, INSERT_DATE,103)= @INSERT_DATE    
    
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)       
SELECT 'GSTR_7_TAX_PAYABLE_TMP' ,count(1) , @INSERT_DATE  FROM [TEST_MPCTD].[dbo].[GSTR_7_TAX_PAYABLE_TMP]     where  CONVERT(DATE, INSERT_DATE,103)= @INSERT_DATE     
    
-------------------------GSTIN-8 RAW TABLES  ------       
    
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)       
 SELECT 'GSTR_8_TCS_TMP' ,count(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[GSTR_8_TCS_TMP]   where  CONVERT(DATE, INSERT_DATE,103)= @INSERT_DATE     
    
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)       
 SELECT 'GSTR_8_TAX_PAID_TMP' ,count(1) , @INSERT_DATE FROM  [TEST_MPCTD].[dbo].[GSTR_8_TAX_PAID_TMP]    where  CONVERT(DATE, INSERT_DATE,103)= @INSERT_DATE     
    
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)       
 SELECT 'GSTR_8_TAX_PAYABLE_TMP' ,count(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[GSTR_8_TAX_PAYABLE_TMP]  where  CONVERT(DATE, INSERT_DATE,103)= @INSERT_DATE       
       
    
   -------------------------REGISTRATION RAW TABLES  ------       
    
    INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)      
   SELECT 'TBL_REG_BANK_DETAILS' ,count(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[TBL_REG_BANK_DETAILS]  where  CONVERT(DATE, INSERTED_DATE,103)= @INSERT_DATE      
    
    INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)      
   SELECT 'TBL_REG_AUTH_OWNER_DETAIL' ,count(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[TBL_REG_AUTH_OWNER_DETAIL]  where  CONVERT(DATE, INSERTED_DATE,103)= @INSERT_DATE      
   
    INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)      
   SELECT 'TBL_REG_REGULAR_TAX_PAYER' ,count(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[TBL_REG_REGULAR_TAX_PAYER]   where  CONVERT(DATE, INSERTED_DATE,103)= @INSERT_DATE      
    
    INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)      
   SELECT 'TBL_REG_TDS_TCS' ,count(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[TBL_REG_TDS_TCS]  where  CONVERT(DATE, INSERTED_DATE,103)= @INSERT_DATE      
    
     
  INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)      
 SELECT 'TBL_REG_GOODS_SERVICE_DETAIL' ,count(1) , @INSERT_DATE FROM [TEST_MPCTD].[dbo].[TBL_REG_GOODS_SERVICE_DETAIL]    where  CONVERT(DATE, INSERTED_DATE,103)= @INSERT_DATE       
     
         
 -------------------------GSTIN_CHALLAN_PAYMENT------        
 INSERT INTO @RECORD_VALIDATION_API (TABLE_NAME , RECORD_COUNT ,INSERT_DATE)          
select 'GSTIN_CHALLAN_PAYMENT_API' , count(1) , @INSERT_DATE  FROM [TEST_MPCTD].[dbo].[TBL_PAYMENT_EOD] where  CONVERT(DATE, INSERT_DATE,103)=  @INSERT_DATE  ;          
         
         
        
   RETURN;            
END;           
        
